### ISSUE TITLE
Errors not checked from server.Serve()

### ISSUE THREAD

**Issue by proglottis** [willbryant/verm#16]
When errors are checked during testing:
```
Unexpected error: accept tcp 127.0.0.1:3407: use of closed network connection
```
I had been getting these errors intermittently while testing. Checking the error seems to make it consistent. Something to do with shutdown perhaps?

**Comment by willbryant** [comment]
Belatedly looking at this.  I don't think I understand - what do you mean by errors are checked @proglottis?

**Comment by proglottis** [comment]
https://github.com/willbryant/verm/blob/57e486c6892ca00aa4910b57485647caab822cef/verm.go#L81-L86
https://github.com/willbryant/verm/blob/57e486c6892ca00aa4910b57485647caab822cef/http_server.go#L29

`server.Serve` returns an error, and there appears to be error checking, but the err from `server.Serve` is never assigned

**Comment by willbryant** [comment]
I see, thanks.

The root of the issue is that some shutdowns return an error: `Unexpected error: accept tcp 127.0.0.1:3407: use of closed network connection`

This happens because in order to make the accepter return, I call `Close` on the Listener.  Golang does not expose `Shutdown` on listeners, so this is the best I could find.

(This causes some other weird failures in tests as the tests that use multiple verm instances, eg. replication tests, currently raise an exception when a verm exits with a failure status, and this prevents those tests continuing on to shut down other verm instances.  The port is then still bound by the verm process that wasn't asked to quit, and subsequent tests will fail.  That I should be able to fix easily enough.)

**Comment by willbryant** [comment]
Looks like even the go http2 library struggles with this.  errClosed is private, so they do string comparison tests to decide if the error is a real error or not:

```
// isClosedConnError reports whether err is an error from use of a closed
// network connection.
func http2isClosedConnError(err error) bool {
	if err == nil {
		return false
	}

	str := err.Error()
	if strings.Contains(str, "use of closed network connection") {
		return true
	}
```

**Comment by willbryant** [comment]
https://blog.golang.org/go1.8 looks like there is now a way to shutdown an HTTP server.  But it would mean no longer supporting go 1.7 and earlier, hmm.

**Comment by proglottis** [comment]
FWIW the go team only support the two latest versions for security patches anyway. So 1.8 is basically the minimum version at the moment (and 1.10 is just around the corner). Might have trouble with distributions lagging I suppose

https://golang.org/doc/devel/release.html#policy

**Comment by willbryant** [comment]
Yeah, the latest Ubuntu LTS still only has 1.6.  No idea what they will do if a security issue comes out!
